### ISSUE TITLE
When to ask for help - time limit

### ISSUE THREAD

**Issue by rkdarst** [bast/help-with-supercomputers#3]
Idea from a colleague of mine: they took the idea "I will work on this problem for one hour, then go to garage and ask for help".  Each problem has a certain time limit that you estimate, then you get help after that time expires.  (of course, guessing a proper time limit is hard, but you try - maybe most important is realizing there is some time limit).

Not sure if related, but there can be levels, like ask your colleague in your office quickly, then work a bit more if they don't know, then move up to the next level of question asking.

**Comment by bast** [comment]
That's great advice! I will use it in real life but also try to bake it into the slide deck.
